config/routes.rb
Rails.application.routes.draw do

  resources :stockfechas
  resources :stockdia
  resources :saldos
  resources :social_media
  resources :boleta
  resources :boleta
  resources :boleta
  mount Spree::Core::Engine, at: '/spree'

  patch '/integracionpay', :to =>  "integracionpay#pay", :as => :integracionpay
  get '/integracionpay' =>  "integracionpay#pay"
  get '/integracionpay/confirm/:id' => "integracionpay#confirm"
  get '/integracionpay/cancel/:id' => "integracionpay#cancel"

  resources :ocs
  resources :skus
  resources :sent_orders
  resources :grupos
  resources :precios
  resources :formulas
  resources :product_orders

scope '/api' do
    scope '/consultar' do
      scope '/:sku' do
        get '/' => 'api#inventarioConsultar'
      end
    end
    scope '/facturas' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#facturarRecibir'
        end
      end
    end
    scope '/oc' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#ocRecibir'
        end
      end
    end
    scope '/pagos' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#pagoRecibir'
        end
      end
    end
    scope '/despachos' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#despachoRecibir'
        end
      end
    end
end   

  get 'socialmedia/search'
  get 'inventario/run'
  get 'home/bodegas'
  get 'home/test'
  get 'receive_orders/receive'
  get 'home/documentacion'
  get 'skus/index'
  get 'skus/new'
  get 'skus/show'
  get 'skus/edit'
  get 'skus/destroy'
  get 'formulas/index'
  get 'formulas/new'
  get 'formulas/show'
  get 'formulas/edit'
  get 'formulas/destroy'
  get 'precios/index'
  get 'precios/new'
  get 'precios/show'
  get 'precios/edit'
  get 'precios/destroy'
  get 'ocs/index'
  get 'ocs/new'
  get 'ocs/show'
  get 'ocs/edit'
  get 'ocs/destroy'  
  get 'sent_orders/index'
  get 'sent_orders/new'
  get 'sent_orders/show'
  get 'sent_orders/edit'
  get 'sent_orders/destroy'
  get 'api/documentacion' => 'home#documentacion'
  get 'api/documentacion'
  get 'home/bodegas'
  
  get 'inventario/vaciar'
  get 'inventario/mover' => 'inventario#moverMiStock'
  get 'saldos/show'
  get 'stockfechas/show'
  get 'home/index'
  
  get 'home/listaOrdenesCompra'
  get 'home/productos'
  get 'home/credenciales'

  root 'home#index'

  get 'home/test'

  get 'home/dashboard'
  get 'home/recibirStock'

  get 'home/insertPromotion'
  get 'home/updatePromotions'
  
Spree::Core::Engine.add_routes do
  namespace :api, :defaults => { :format => 'json' } do
    resources :option_values
  end
end

end

app/models/product_order.rb
class ProductOrder < ActiveRecord::Base
end

app/controllers/product_orders_controller.rb
class ProductOrdersController < ApplicationController
  before_action :set_product_order, only: [:show, :edit, :update, :destroy]

  # GET /product_orders
  # GET /product_orders.json
  def index
    @product_orders = ProductOrder.all
  end

  # GET /product_orders/1
  # GET /product_orders/1.json
  def show
  end

  # GET /product_orders/new
  def new
    @product_order = ProductOrder.new
  end

  # GET /product_orders/1/edit
  def edit
  end

  # POST /product_orders
  # POST /product_orders.json
  def create
    @product_order = ProductOrder.new(product_order_params)

    respond_to do |format|
      if @product_order.save
        format.html { redirect_to @product_order, notice: 'Product order was successfully created.' }
        format.json { render :show, status: :created, location: @product_order }
      else
        format.html { render :new }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_orders/1
  # PATCH/PUT /product_orders/1.json
  def update
    respond_to do |format|
      if @product_order.update(product_order_params)
        format.html { redirect_to @product_order, notice: 'Product order was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_order }
      else
        format.html { render :edit }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_orders/1
  # DELETE /product_orders/1.json
  def destroy
    @product_order.destroy
    respond_to do |format|
      format.html { redirect_to product_orders_url, notice: 'Product order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_order
      @product_order = ProductOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_order_params
      params.require(:product_order).permit(:sku, :cantidad, :disponibe)
    end
end

app/helpers/product_orders_helper.rb
module ProductOrdersHelper
end

app/views/product_orders/_form.html.erb
<%= form_for(@product_order) do |f| %>
  <% if @product_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_order.errors.count, "error") %> prohibited this product_order from being saved:</h2>

      <ul>
      <% @product_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sku %><br>
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :disponibe %><br>
    <%= f.datetime_select :disponibe %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_orders/edit.html.erb
<h1>Editing Product Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_order %> |
<%= link_to 'Back', product_orders_path %>

app/views/product_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Orders</h1>

<table>
  <thead>
    <tr>
      <th>Sku</th>
      <th>Cantidad</th>
      <th>Disponibe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_orders.each do |product_order| %>
      <tr>
        <td><%= product_order.sku %></td>
        <td><%= product_order.cantidad %></td>
        <td><%= product_order.disponibe %></td>
        <td><%= link_to 'Show', product_order %></td>
        <td><%= link_to 'Edit', edit_product_order_path(product_order) %></td>
        <td><%= link_to 'Destroy', product_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product order', new_product_order_path %>

app/views/product_orders/new.html.erb
<h1>New Product Order</h1>

<%= render 'form' %>

<%= link_to 'Back', product_orders_path %>

app/views/product_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sku:</strong>
  <%= @product_order.sku %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @product_order.cantidad %>
</p>

<p>
  <strong>Disponibe:</strong>
  <%= @product_order.disponibe %>
</p>

<%= link_to 'Edit', edit_product_order_path(@product_order) %> |
<%= link_to 'Back', product_orders_path %>