config/routes.rb
Rails.application.routes.draw do

  resources :stockfechas
  resources :stockdia
  resources :saldos
  resources :social_media
  resources :boleta
  resources :boleta
  resources :boleta
  mount Spree::Core::Engine, at: '/spree'

  patch '/integracionpay', :to =>  "integracionpay#pay", :as => :integracionpay
  get '/integracionpay' =>  "integracionpay#pay"
  get '/integracionpay/confirm/:id' => "integracionpay#confirm"
  get '/integracionpay/cancel/:id' => "integracionpay#cancel"

  resources :ocs
  resources :skus
  resources :sent_orders
  resources :grupos
  resources :precios
  resources :formulas
  resources :product_orders

scope '/api' do
    scope '/consultar' do
      scope '/:sku' do
        get '/' => 'api#inventarioConsultar'
      end
    end
    scope '/facturas' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#facturarRecibir'
        end
      end
    end
    scope '/oc' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#ocRecibir'
        end
      end
    end
    scope '/pagos' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#pagoRecibir'
        end
      end
    end
    scope '/despachos' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#despachoRecibir'
        end
      end
    end
end   

  get 'socialmedia/search'
  get 'inventario/run'
  get 'home/bodegas'
  get 'home/test'
  get 'receive_orders/receive'
  get 'home/documentacion'
  get 'skus/index'
  get 'skus/new'
  get 'skus/show'
  get 'skus/edit'
  get 'skus/destroy'
  get 'formulas/index'
  get 'formulas/new'
  get 'formulas/show'
  get 'formulas/edit'
  get 'formulas/destroy'
  get 'precios/index'
  get 'precios/new'
  get 'precios/show'
  get 'precios/edit'
  get 'precios/destroy'
  get 'ocs/index'
  get 'ocs/new'
  get 'ocs/show'
  get 'ocs/edit'
  get 'ocs/destroy'  
  get 'sent_orders/index'
  get 'sent_orders/new'
  get 'sent_orders/show'
  get 'sent_orders/edit'
  get 'sent_orders/destroy'
  get 'api/documentacion' => 'home#documentacion'
  get 'api/documentacion'
  get 'home/bodegas'
  
  get 'inventario/vaciar'
  get 'inventario/mover' => 'inventario#moverMiStock'
  get 'saldos/show'
  get 'stockfechas/show'
  get 'home/index'
  
  get 'home/listaOrdenesCompra'
  get 'home/productos'
  get 'home/credenciales'

  root 'home#index'

  get 'home/test'

  get 'home/dashboard'
  get 'home/recibirStock'

  get 'home/insertPromotion'
  get 'home/updatePromotions'
  
Spree::Core::Engine.add_routes do
  namespace :api, :defaults => { :format => 'json' } do
    resources :option_values
  end
end

end

app/models/saldo.rb
class Saldo < ActiveRecord::Base
end

app/controllers/saldos_controller.rb
class SaldosController < ApplicationController
  before_action :set_saldo, only: [:show, :edit, :update, :destroy]

  # GET /saldos
  # GET /saldos.json
  def index
    @saldos = Saldo.all
  end

  # GET /saldos/1
  # GET /saldos/1.json
  def show
  end

  # GET /saldos/new
  def new
    @saldo = Saldo.new
  end

  # GET /saldos/1/edit
  def edit
  end

  # POST /saldos
  # POST /saldos.json
  def create
    @saldo = Saldo.new(saldo_params)

    respond_to do |format|
      if @saldo.save
        format.html { redirect_to @saldo, notice: 'Saldo was successfully created.' }
        format.json { render :show, status: :created, location: @saldo }
      else
        format.html { render :new }
        format.json { render json: @saldo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saldos/1
  # PATCH/PUT /saldos/1.json
  def update
    respond_to do |format|
      if @saldo.update(saldo_params)
        format.html { redirect_to @saldo, notice: 'Saldo was successfully updated.' }
        format.json { render :show, status: :ok, location: @saldo }
      else
        format.html { render :edit }
        format.json { render json: @saldo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saldos/1
  # DELETE /saldos/1.json
  def destroy
    @saldo.destroy
    respond_to do |format|
      format.html { redirect_to saldos_url, notice: 'Saldo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saldo
      @saldo = Saldo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saldo_params
      params.require(:saldo).permit(:fecha, :monto)
    end
end

app/helpers/saldos_helper.rb
module SaldosHelper
end

app/views/saldos/_form.html.erb
<%= form_for(@saldo) do |f| %>
  <% if @saldo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saldo.errors.count, "error") %> prohibited this saldo from being saved:</h2>

      <ul>
      <% @saldo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :monto %><br>
    <%= f.number_field :monto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/saldos/edit.html.erb
<h1>Editing Saldo</h1>

<%= render 'form' %>

<%= link_to 'Show', @saldo %> |
<%= link_to 'Back', saldos_path %>

app/views/saldos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Saldos</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Monto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @saldos.each do |saldo| %>
      <tr>
        <td><%= saldo.fecha %></td>
        <td><%= saldo.monto %></td>
        <td><%= link_to 'Show', saldo %></td>
        <td><%= link_to 'Edit', edit_saldo_path(saldo) %></td>
        <td><%= link_to 'Destroy', saldo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Saldo', new_saldo_path %>

app/views/saldos/new.html.erb
<h1>New Saldo</h1>

<%= render 'form' %>

<%= link_to 'Back', saldos_path %>

app/views/saldos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @saldo.fecha %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @saldo.monto %>
</p>

<%= link_to 'Edit', edit_saldo_path(@saldo) %> |
<%= link_to 'Back', saldos_path %>