config/routes.rb
Rails.application.routes.draw do

  resources :stockfechas
  resources :stockdia
  resources :saldos
  resources :social_media
  resources :boleta
  resources :boleta
  resources :boleta
  mount Spree::Core::Engine, at: '/spree'

  patch '/integracionpay', :to =>  "integracionpay#pay", :as => :integracionpay
  get '/integracionpay' =>  "integracionpay#pay"
  get '/integracionpay/confirm/:id' => "integracionpay#confirm"
  get '/integracionpay/cancel/:id' => "integracionpay#cancel"

  resources :ocs
  resources :skus
  resources :sent_orders
  resources :grupos
  resources :precios
  resources :formulas
  resources :product_orders

scope '/api' do
    scope '/consultar' do
      scope '/:sku' do
        get '/' => 'api#inventarioConsultar'
      end
    end
    scope '/facturas' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#facturarRecibir'
        end
      end
    end
    scope '/oc' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#ocRecibir'
        end
      end
    end
    scope '/pagos' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#pagoRecibir'
        end
      end
    end
    scope '/despachos' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#despachoRecibir'
        end
      end
    end
end   

  get 'socialmedia/search'
  get 'inventario/run'
  get 'home/bodegas'
  get 'home/test'
  get 'receive_orders/receive'
  get 'home/documentacion'
  get 'skus/index'
  get 'skus/new'
  get 'skus/show'
  get 'skus/edit'
  get 'skus/destroy'
  get 'formulas/index'
  get 'formulas/new'
  get 'formulas/show'
  get 'formulas/edit'
  get 'formulas/destroy'
  get 'precios/index'
  get 'precios/new'
  get 'precios/show'
  get 'precios/edit'
  get 'precios/destroy'
  get 'ocs/index'
  get 'ocs/new'
  get 'ocs/show'
  get 'ocs/edit'
  get 'ocs/destroy'  
  get 'sent_orders/index'
  get 'sent_orders/new'
  get 'sent_orders/show'
  get 'sent_orders/edit'
  get 'sent_orders/destroy'
  get 'api/documentacion' => 'home#documentacion'
  get 'api/documentacion'
  get 'home/bodegas'
  
  get 'inventario/vaciar'
  get 'inventario/mover' => 'inventario#moverMiStock'
  get 'saldos/show'
  get 'stockfechas/show'
  get 'home/index'
  
  get 'home/listaOrdenesCompra'
  get 'home/productos'
  get 'home/credenciales'

  root 'home#index'

  get 'home/test'

  get 'home/dashboard'
  get 'home/recibirStock'

  get 'home/insertPromotion'
  get 'home/updatePromotions'
  
Spree::Core::Engine.add_routes do
  namespace :api, :defaults => { :format => 'json' } do
    resources :option_values
  end
end

end

app/models/stockfecha.rb
class Stockfecha < ActiveRecord::Base
end

app/controllers/stockfechas_controller.rb
class StockfechasController < ApplicationController
  before_action :set_stockfecha, only: [:show, :edit, :update, :destroy]

  # GET /stockfechas
  # GET /stockfechas.json
  def index
    @stockfechas = Stockfecha.all
  end

  # GET /stockfechas/1
  # GET /stockfechas/1.json
  def show
  end

  # GET /stockfechas/new
  def new
    @stockfecha = Stockfecha.new
  end

  # GET /stockfechas/1/edit
  def edit
  end

  # POST /stockfechas
  # POST /stockfechas.json
  def create
    @stockfecha = Stockfecha.new(stockfecha_params)

    respond_to do |format|
      if @stockfecha.save
        format.html { redirect_to @stockfecha, notice: 'Stockfecha was successfully created.' }
        format.json { render :show, status: :created, location: @stockfecha }
      else
        format.html { render :new }
        format.json { render json: @stockfecha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stockfechas/1
  # PATCH/PUT /stockfechas/1.json
  def update
    respond_to do |format|
      if @stockfecha.update(stockfecha_params)
        format.html { redirect_to @stockfecha, notice: 'Stockfecha was successfully updated.' }
        format.json { render :show, status: :ok, location: @stockfecha }
      else
        format.html { render :edit }
        format.json { render json: @stockfecha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stockfechas/1
  # DELETE /stockfechas/1.json
  def destroy
    @stockfecha.destroy
    respond_to do |format|
      format.html { redirect_to stockfechas_url, notice: 'Stockfecha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stockfecha
      @stockfecha = Stockfecha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stockfecha_params
      params.require(:stockfecha).permit(:fecha, :sku, :cantidad)
    end
end

app/helpers/stockfechas_helper.rb
module StockfechasHelper
end

app/views/stockfechas/_form.html.erb
<%= form_for(@stockfecha) do |f| %>
  <% if @stockfecha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stockfecha.errors.count, "error") %> prohibited this stockfecha from being saved:</h2>

      <ul>
      <% @stockfecha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :sku %><br>
    <%= f.number_field :sku %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stockfechas/edit.html.erb
<h1>Editing Stockfecha</h1>

<%= render 'form' %>

<%= link_to 'Show', @stockfecha %> |
<%= link_to 'Back', stockfechas_path %>

app/views/stockfechas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stockfechas</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Sku</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stockfechas.each do |stockfecha| %>
      <tr>
        <td><%= stockfecha.fecha %></td>
        <td><%= stockfecha.sku %></td>
        <td><%= stockfecha.cantidad %></td>
        <td><%= link_to 'Show', stockfecha %></td>
        <td><%= link_to 'Edit', edit_stockfecha_path(stockfecha) %></td>
        <td><%= link_to 'Destroy', stockfecha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stockfecha', new_stockfecha_path %>

app/views/stockfechas/new.html.erb
<h1>New Stockfecha</h1>

<%= render 'form' %>

<%= link_to 'Back', stockfechas_path %>

app/views/stockfechas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @stockfecha.fecha %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @stockfecha.sku %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @stockfecha.cantidad %>
</p>

<%= link_to 'Edit', edit_stockfecha_path(@stockfecha) %> |
<%= link_to 'Back', stockfechas_path %>