config/routes.rb
Rails.application.routes.draw do

  resources :stockfechas
  resources :stockdia
  resources :saldos
  resources :social_media
  resources :boleta
  resources :boleta
  resources :boleta
  mount Spree::Core::Engine, at: '/spree'

  patch '/integracionpay', :to =>  "integracionpay#pay", :as => :integracionpay
  get '/integracionpay' =>  "integracionpay#pay"
  get '/integracionpay/confirm/:id' => "integracionpay#confirm"
  get '/integracionpay/cancel/:id' => "integracionpay#cancel"

  resources :ocs
  resources :skus
  resources :sent_orders
  resources :grupos
  resources :precios
  resources :formulas
  resources :product_orders

scope '/api' do
    scope '/consultar' do
      scope '/:sku' do
        get '/' => 'api#inventarioConsultar'
      end
    end
    scope '/facturas' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#facturarRecibir'
        end
      end
    end
    scope '/oc' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#ocRecibir'
        end
      end
    end
    scope '/pagos' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#pagoRecibir'
        end
      end
    end
    scope '/despachos' do
      scope '/recibir' do
        scope '/:id' do
          get '/' => 'api#despachoRecibir'
        end
      end
    end
end   

  get 'socialmedia/search'
  get 'inventario/run'
  get 'home/bodegas'
  get 'home/test'
  get 'receive_orders/receive'
  get 'home/documentacion'
  get 'skus/index'
  get 'skus/new'
  get 'skus/show'
  get 'skus/edit'
  get 'skus/destroy'
  get 'formulas/index'
  get 'formulas/new'
  get 'formulas/show'
  get 'formulas/edit'
  get 'formulas/destroy'
  get 'precios/index'
  get 'precios/new'
  get 'precios/show'
  get 'precios/edit'
  get 'precios/destroy'
  get 'ocs/index'
  get 'ocs/new'
  get 'ocs/show'
  get 'ocs/edit'
  get 'ocs/destroy'  
  get 'sent_orders/index'
  get 'sent_orders/new'
  get 'sent_orders/show'
  get 'sent_orders/edit'
  get 'sent_orders/destroy'
  get 'api/documentacion' => 'home#documentacion'
  get 'api/documentacion'
  get 'home/bodegas'
  
  get 'inventario/vaciar'
  get 'inventario/mover' => 'inventario#moverMiStock'
  get 'saldos/show'
  get 'stockfechas/show'
  get 'home/index'
  
  get 'home/listaOrdenesCompra'
  get 'home/productos'
  get 'home/credenciales'

  root 'home#index'

  get 'home/test'

  get 'home/dashboard'
  get 'home/recibirStock'

  get 'home/insertPromotion'
  get 'home/updatePromotions'
  
Spree::Core::Engine.add_routes do
  namespace :api, :defaults => { :format => 'json' } do
    resources :option_values
  end
end

end

app/models/precio.rb
class Precio < ActiveRecord::Base
end

app/controllers/precios_controller.rb
class PreciosController < ApplicationController
  before_action :set_precio, only: [:show, :edit, :update, :destroy]

  # GET /precios
  # GET /precios.json
  def index
    @precios = Precio.all
  end

  # GET /precios/1
  # GET /precios/1.json
  def show
  end

  # GET /precios/new
  def new
    @precio = Precio.new
  end

  # GET /precios/1/edit
  def edit
  end

  # POST /precios
  # POST /precios.json
  def create
    @precio = Precio.new(precio_params)

    respond_to do |format|
      if @precio.save
        format.html { redirect_to @precio, notice: 'Precio was successfully created.' }
        format.json { render :show, status: :created, location: @precio }
      else
        format.html { render :new }
        format.json { render json: @precio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /precios/1
  # PATCH/PUT /precios/1.json
  def update
    respond_to do |format|
      if @precio.update(precio_params)
        format.html { redirect_to @precio, notice: 'Precio was successfully updated.' }
        format.json { render :show, status: :ok, location: @precio }
      else
        format.html { render :edit }
        format.json { render json: @precio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /precios/1
  # DELETE /precios/1.json
  def destroy
    @precio.destroy
    respond_to do |format|
      format.html { redirect_to precios_url, notice: 'Precio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_precio
      @precio = Precio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def precio_params
      params.require(:precio).permit(:sku, :descripcion, :precioUnitario)
    end
end

app/helpers/precios_helper.rb
module PreciosHelper
end

app/views/precios/_form.html.erb
<%= form_for(@precio) do |f| %>
  <% if @precio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@precio.errors.count, "error") %> prohibited this precio from being saved:</h2>

      <ul>
      <% @precio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sku %><br>
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :precioUnitario %><br>
    <%= f.number_field :precioUnitario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/precios/edit.html.erb
<h1>Editing Precio</h1>

<%= render 'form' %>

<%= link_to 'Show', @precio %> |
<%= link_to 'Back', precios_path %>

app/views/precios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Precios</h1>

<table>
  <thead>
    <tr>
      <th>Sku</th>
      <th>Descripcion</th>
      <th>Preciounitario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @precios.each do |precio| %>
      <tr>
        <td><%= precio.sku %></td>
        <td><%= precio.descripcion %></td>
        <td><%= precio.precioUnitario %></td>
        <td><%= link_to 'Show', precio %></td>
        <td><%= link_to 'Edit', edit_precio_path(precio) %></td>
        <td><%= link_to 'Destroy', precio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Precio', new_precio_path %>

app/views/precios/new.html.erb
<h1>New Precio</h1>

<%= render 'form' %>

<%= link_to 'Back', precios_path %>

app/views/precios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sku:</strong>
  <%= @precio.sku %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @precio.descripcion %>
</p>

<p>
  <strong>Preciounitario:</strong>
  <%= @precio.precioUnitario %>
</p>

<%= link_to 'Edit', edit_precio_path(@precio) %> |
<%= link_to 'Back', precios_path %>